In [49]:
import math
import numpy as np
import pandas as pd

In [50]:
data2 = 'sarimaxdataset.csv'
dataset2 = pd.read_csv(data2)
dataset2.head(5)

Datetime  PM2.5  NO2  NH3  CO     O3   AQI
0  2021-01-17 10:00:00  45.31  NaN  NaN NaN   3.04  90.0
1  2021-01-17 11:00:00  44.60  NaN  NaN NaN   7.21  87.0
2  2021-01-17 12:00:00  39.12  NaN  NaN NaN  14.03  77.0
3  2021-01-17 13:00:00  35.20  NaN  NaN NaN  20.43  69.0
4  2021-01-17 14:00:00  32.67  NaN  NaN NaN  21.31  65.0

In [51]:
dataset2.columns=['Datetime','PM2.5','NO2','NH3','CO','O3','AQI']
dataset2.interpolate(limit_direction="both",inplace=True)
dataset2.head(5)

Datetime  PM2.5    NO2     NH3    CO     O3   AQI
0  2021-01-17 10:00:00  45.31  11.52  133.01  1.37   3.04  90.0
1  2021-01-17 11:00:00  44.60  11.52  133.01  1.37   7.21  87.0
2  2021-01-17 12:00:00  39.12  11.52  133.01  1.37  14.03  77.0
3  2021-01-17 13:00:00  35.20  11.52  133.01  1.37  20.43  69.0
4  2021-01-17 14:00:00  32.67  11.52  133.01  1.37  21.31  65.0

In [52]:
from statsmodels.tsa.statespace.sarimax import SARIMAX
dataset2.set_index(dataset2['Datetime'],inplace=True)
dataset2.head(5)

Datetime  PM2.5    NO2     NH3    CO     O3  \
Datetime                                                                      
2021-01-17 10:00:00  2021-01-17 10:00:00  45.31  11.52  133.01  1.37   3.04   
2021-01-17 11:00:00  2021-01-17 11:00:00  44.60  11.52  133.01  1.37   7.21   
2021-01-17 12:00:00  2021-01-17 12:00:00  39.12  11.52  133.01  1.37  14.03   
2021-01-17 13:00:00  2021-01-17 13:00:00  35.20  11.52  133.01  1.37  20.43   
2021-01-17 14:00:00  2021-01-17 14:00:00  32.67  11.52  133.01  1.37  21.31   

                      AQI  
Datetime                   
2021-01-17 10:00:00  90.0  
2021-01-17 11:00:00  87.0  
2021-01-17 12:00:00  77.0  
2021-01-17 13:00:00  69.0  
2021-01-17 14:00:00  65.0

In [53]:
dataset2=dataset2.drop(columns=['Datetime'],axis=1)
dataset2.head(5)

PM2.5    NO2     NH3    CO     O3   AQI
Datetime                                                    
2021-01-17 10:00:00  45.31  11.52  133.01  1.37   3.04  90.0
2021-01-17 11:00:00  44.60  11.52  133.01  1.37   7.21  87.0
2021-01-17 12:00:00  39.12  11.52  133.01  1.37  14.03  77.0
2021-01-17 13:00:00  35.20  11.52  133.01  1.37  20.43  69.0
2021-01-17 14:00:00  32.67  11.52  133.01  1.37  21.31  65.0

In [54]:
df = dataset2.copy()
df.head(5)

PM2.5    NO2     NH3    CO     O3   AQI
Datetime                                                    
2021-01-17 10:00:00  45.31  11.52  133.01  1.37   3.04  90.0
2021-01-17 11:00:00  44.60  11.52  133.01  1.37   7.21  87.0
2021-01-17 12:00:00  39.12  11.52  133.01  1.37  14.03  77.0
2021-01-17 13:00:00  35.20  11.52  133.01  1.37  20.43  69.0
2021-01-17 14:00:00  32.67  11.52  133.01  1.37  21.31  65.0

In [55]:
actual=df.tail(5)['AQI'].tolist()
print(actual)

[116.0, 111.0, 109.0, 107.0, 102.0]


In [56]:
df = df.iloc[:-5]

In [57]:
e = pd.DataFrame(df[['PM2.5','NO2','NH3','O3','CO']].values)


In [58]:
model = SARIMAX(list(df['AQI']),exog=e,order=(1,0,1),seasonal_order=(1,0,1,24),enforce_invertibility=False)
results = model.fit()

C:\Users\sanju\Anaconda3\lib\site-packages\statsmodels\base\model.py:512: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


In [59]:
exog_forecast = e[1684:].values
fcast = results.predict(len(df),len(df)+4,exog=exog_forecast)

In [67]:
y = fcast.values
y = y.ravel()
print("Forecasted AQI:")
print(y)

Forecasted AQI:
[108.90167444 105.7297055  104.92049579 105.38284937 111.56817646]


In [68]:
from sklearn.metrics import mean_squared_error
from math import sqrt

#calculate RMSE
r = sqrt(mean_squared_error(actual, y)) 
print("RMSE:")
print(r)

RMSE:
6.147678608556362


In [5]:
#PM2.5 removed

import math
import numpy as np
import pandas as pd

data2 = 'sarimaxdataset.csv'

dataset2 = pd.read_csv(data2)

dataset2.columns=['Datetime','PM2.5','NO2','NH3','CO','O3','AQI']

dataset2 = dataset2.drop(columns=['PM2.5'],axis=1)

dataset2.head()

dataset2.interpolate(limit_direction="both",inplace=True)

from statsmodels.tsa.statespace.sarimax import SARIMAX

dataset2.set_index(dataset2['Datetime'],inplace=True)

dataset2=dataset2.drop(columns=['Datetime'],axis=1)
dataset2.head()

df = dataset2.copy()
df.tail()
e = pd.DataFrame(df[['NO2','NH3','O3','CO']].values)
model = SARIMAX(list(df['AQI']),exog=e,order=(1,0,1),seasonal_order=(1,0,1,24),enforce_invertibility=False)
results = model.fit()
exog_forecast = e[1684:].values
fcast = results.predict(len(df),len(df)+4,exog=exog_forecast)
y = fcast.values
y = y.ravel()
print("Forecasted AQI:")
print(y)


C:\Users\sanju\Anaconda3\lib\site-packages\statsmodels\base\model.py:512: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


Forecasted AQI:
[120.66176993 114.70096696 112.45337077 108.03420112 107.5171574 ]


In [6]:
actual = [116.0, 111.0, 109.0, 107.0, 102.0]

from sklearn.metrics import mean_squared_error
from math import sqrt

#calculate RMSE
r = sqrt(mean_squared_error(actual, y)) 
print("RMSE:")
print(r)

RMSE:
6.470910989242351


In [106]:
#NO2 removed

import math
import numpy as np
import pandas as pd

data2 = 'sarimaxdataset.csv'

dataset2 = pd.read_csv(data2)

dataset2.columns=['Datetime','PM2.5','NO2','NH3','CO','O3','AQI']

dataset2 = dataset2.drop(columns=['NO2'],axis=1)

dataset2.interpolate(limit_direction="both",inplace=True)

from statsmodels.tsa.statespace.sarimax import SARIMAX

dataset2.set_index(dataset2['Datetime'],inplace=True)

dataset2=dataset2.drop(columns=['Datetime'],axis=1)
dataset2.head()

df = dataset2.copy()
df.tail()
e = pd.DataFrame(df[['PM2.5','NH3','O3','CO']].values)
model = SARIMAX(list(df['AQI']),exog=e,order=(1,0,1),seasonal_order=(1,0,1,24),enforce_invertibility=False)
results = model.fit()
exog_forecast = e[1684:].values
fcast = results.predict(len(df),len(df)+4,exog=exog_forecast)
y = fcast.values
y = y.ravel()
print("Forecasted AQI:")
print(y)
actual = [116.0, 111.0, 109.0, 107.0, 102.0]


from sklearn.metrics import mean_squared_error
from math import sqrt

#calculate RMSE
r = sqrt(mean_squared_error(actual, y)) 
print("RMSE:")
print(r)

C:\Users\ssneh\anaconda3\lib\site-packages\statsmodels\base\model.py:568: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


Forecasted AQI:
[108.70355026 105.5287681  104.92998817 105.39740033 111.36245886]
RMSE:
6.163789665468293


In [107]:
#NH3 removed

import math
import numpy as np
import pandas as pd

data2 = 'sarimaxdataset.csv'

dataset2 = pd.read_csv(data2)

dataset2.columns=['Datetime','PM2.5','NO2','NH3','CO','O3','AQI']

dataset2 = dataset2.drop(columns=['NH3'],axis=1)

dataset2.interpolate(limit_direction="both",inplace=True)

from statsmodels.tsa.statespace.sarimax import SARIMAX

dataset2.set_index(dataset2['Datetime'],inplace=True)

dataset2=dataset2.drop(columns=['Datetime'],axis=1)
dataset2.head()

df = dataset2.copy()
df.tail()

e = pd.DataFrame(df[['PM2.5','NO2','O3','CO']].values)

model = SARIMAX(list(df['AQI']),exog=e,order=(1,0,1),seasonal_order=(1,0,1,24),enforce_invertibility=False)
results = model.fit()

exog_forecast = e[1684:].values
fcast = results.predict(len(df),len(df)+4,exog=exog_forecast)
y = fcast.values
y = y.ravel()
print("Forecasted AQI:")
print(y)

actual = [116.0, 111.0, 109.0, 107.0, 102.0]


from sklearn.metrics import mean_squared_error
from math import sqrt

#calculate RMSE
r = sqrt(mean_squared_error(actual, y)) 
print("RMSE:")
print(r)

C:\Users\ssneh\anaconda3\lib\site-packages\statsmodels\base\model.py:568: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


Forecasted AQI:
[108.07811518 104.45471377 105.88521851 106.86436941 110.82114058]
RMSE:
6.214978866560837


In [108]:
#CO removed

import math
import numpy as np
import pandas as pd

data2 = 'sarimaxdataset.csv'

dataset2 = pd.read_csv(data2)

dataset2.columns=['Datetime','PM2.5','NO2','NH3','CO','O3','AQI']

dataset2 =  dataset2.drop(columns=['CO'],axis=1)

dataset2.interpolate(limit_direction="both",inplace=True)

from statsmodels.tsa.statespace.sarimax import SARIMAX

dataset2.set_index(dataset2['Datetime'],inplace=True)

dataset2=dataset2.drop(columns=['Datetime'],axis=1)
dataset2.head()

df = dataset2.copy()
df.tail()

e = pd.DataFrame(df[['PM2.5','NO2','NH3','O3']].values)

model = SARIMAX(list(df['AQI']),exog=e,order=(1,0,1),seasonal_order=(1,0,1,24),enforce_invertibility=False)
results = model.fit()

exog_forecast = e[1684:].values
fcast = results.predict(len(df),len(df)+4,exog=exog_forecast)
y = fcast.values
y = y.ravel()
print("Forecasted AQI:")
print(y)

actual = [116.0, 111.0, 109.0, 107.0, 102.0]


from sklearn.metrics import mean_squared_error
from math import sqrt

#calculate RMSE
r = sqrt(mean_squared_error(actual, y)) 
print("RMSE:")
print(r)

Forecasted AQI:
[108.92242753 105.74722085 105.05216724 105.36919538 111.6396842 ]
RMSE:
6.145765036639948


In [109]:
#O3 removed

import math
import numpy as np
import pandas as pd

data2 = 'sarimaxdataset.csv'

dataset2 = pd.read_csv(data2)

dataset2.columns=['Datetime','PM2.5','NO2','NH3','CO','O3','AQI']

dataset2 =  dataset2.drop(columns=['O3'],axis=1)

dataset2.interpolate(limit_direction="both",inplace=True)

from statsmodels.tsa.statespace.sarimax import SARIMAX

dataset2.set_index(dataset2['Datetime'],inplace=True)

dataset2=dataset2.drop(columns=['Datetime'],axis=1)
dataset2.head()

df = dataset2.copy()
df.tail()

e = pd.DataFrame(df[['PM2.5','NO2','NH3','CO']].values)

model = SARIMAX(list(df['AQI']),exog=e,order=(1,0,1),seasonal_order=(1,0,1,24),enforce_invertibility=False)
results = model.fit()

exog_forecast = e[1684:].values
fcast = results.predict(len(df),len(df)+4,exog=exog_forecast)
y = fcast.values
y = y.ravel()
print("Forecasted AQI:")
print(y)

actual = [116.0, 111.0, 109.0, 107.0, 102.0]


from sklearn.metrics import mean_squared_error
from math import sqrt

#calculate RMSE
r = sqrt(mean_squared_error(actual, y)) 
print("RMSE:")
print(r)

Forecasted AQI:
[108.38826546 105.65262853 104.82380481 105.16810891 111.29748977]
RMSE:
6.225313353359774
